# Setup
title: 'Homepage of Riccardo Pelizzi'
description: >
  This is the personal homepage of Riccardo Pelizzi, Software Engineer at
  Google and Ph.D. Graduate from Stony Brook University. This site contains
  personal information, a curriculum vitae and updates about my work, research
  and publications.
url: http://pelizzi.com


# About/contact
author:
  name:  Riccardo Pelizzi
  email: r.pelizzi@gmail.com
